version: '3.2'

services:

  api:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: "app-api"
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ../:/var/www
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ../logs/api:/var/log/nginx
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    container_name: "app"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    image: postgres
    container_name: "db"
    volumes:
      - db:/var/lib/postgresql/data
      - ./database:/var/home
    restart: always
    ports:
      - "2727:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=dbname
      - POSTGRES_PASSWORD=dbuser
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.201.0.0/28

volumes:
  db:
    driver: local